spring.profiles.active=dev
spring.application.name=Juan-platzi-play
server.servlet.context-path=/platzi-play/api
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver