server.port=8080

# Spring Data JPA
#Base Interna de render
spring.datasource.url=jdbc:postgresql://dpg-dapfhc3bc2fs73fierfg-a:5432/platzi_play_db_c36b
#Base Externa de render
#spring.datasource.url=jdbc:postgresql://dpg-dapfhc3bc2fs73fierfg-a.oregon-postgres.render.com:5432/platzi_play_db_c36b
spring.datasource.username=juanlv
spring.datasource.password=sdqZKOP5hFMPhsdzcDeIJj8TMbFw7BC5

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# LangChain4j
spring.config.import=optional:file:../../.env[.properties]
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
